[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "kiwi toilet kidney spy note goat degree estate earn swear plate text task reveal park firm chest afford debris merry series system army talk"
